# hit the balls to gain points
# instead if the robot hits the wall, it loses points

[simulation]
	numrobot = 1
	numobject = 3
	map = "simple_square"
	actuators = ["MotionVW", "Keyboard"]
	sensors = ["Pose", "Proximity", "Infrared"]
	[[simulation.objects]]
		file = "target"
		name = "GOAL"
		x = 5
		y = 5
		z = 0.01
		[simulation.objects.properties]
			Label = "GOAL"
			GOAL = true
	[[simulation.camera_position]]
		x_cam = -18.0
		y_cam = -6.7
		z_cam = 10.8
		p_cam = 1.09
		q_cam = 0
		r_cam = -1.14
	[[simulation.robot_position]]
		x = 1
		y = 1
		z = 0
		p = 0
		q = 0
		r = 0
	[simulation.time]
		totalTime = 5
		simulationStopMode = "stopWhenNoTime"
	[simulation.initScore]
		k = 0
		initialScore = 0
		stopFlag = false
	[[simulation.score]]
		obj = "Wall"
		score = -10
		stop = false
