SAMPLE_TIME = 0.2
RISK_OF_COLLISION_DISTANCE = 1.5

BOUNDARY_FOLLOWING_LINEAR_SPEED = 2
BOUNDARY_FOLLOWING_ANGULAR_VELOCITY = 2
BOUNDARY_FOLLOWING_MAX_FREE_SPACE = 1.5
BOUNDARY_FOLLOWING_MIN_FREE_SPACE = 1

MOTION_TO_GOAL_LINEAR_SPEED = 2
MOTION_TO_GOAL_ANGULAR_VELOCITY = 2
MOTION_TO_GOAL_TRAJECTORY_CORRECTION_INTERVAL = 2

BUG_2_LINE_TOLERANCE = 0.5
BUG_2_INITIAL_POSITION_TOLERANCE = 2
